# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a645edcacd8c7488107b1158743b77637eae37017d37d127f64b30f37d273bce734cd920df5a7b40ab772ed008f545bc9ee934454165e891c296db57901a53b

test:
  secret_key_base: 583d7b2d0ee32844882dbdaa1e40681eba0e7edd5e3564ed4854ae33b19f052b2a174041d2d5d258740b61d74d3387d594a2a9f37350e6d90fec8620f1dfa6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
